#!/usr/bin/env python3
import  yaml

ROOT_URL = "http://www.ifma.org.il/BRPortal/br/P100.jsp"
LOCAL_STORAGE_PATH = "yidxsfpt/"

white_list = { }    
white_list["www.ifma.org.il"]    = [ "" ]   #Everything under this domain is included 
white_list["www.ifma.022.co.il"] = [ "" ]   #Everything under this domain is included 
white_list["www.understending-math.022.co.il"] = [ "" ]   #Everything under this domain is included
white_list["www.022.co.il"] = [ "/BRPortal/resources", "BRPortal/resources" ]   
white_list["www.files.org.il"] = [ "BRPortalStorage" ]   

config = { }
config["ROOT_URL"] = ROOT_URL
config["LOCAL_STORAGE_PATH"] = LOCAL_STORAGE_PATH
config["white_list"] = white_list
yaml.dump(config, open("new_config.yaml", 'w') )

print("Wrote a new config file at: new_config.yaml")
