#!/usr/bin/env python3
import urls, yaml

config = yaml.safe_load(open("config.yaml"))
u = urls.URLs(config["ROOT_URL"], config["LOCAL_STORAGE_PATH"])
u.setWhiteList(config["white_list"])
u.MAX_DEPTH_TO_FETCH = int(config["MAX_DEPTH_TO_FETCH"])

numFetched = 1; numFilesModified = 1
while numFetched or numFilesModified:
    u.logStats()
    numFetched = u.fetchIfNeeded()
    numFilesModified = u.analyzeAllFetchedFiles()


